
enum City: CaseIterable {
    case newYork
    case losAngeles
    case chicago
    case miami
    case dallas
    case philadelphia
    case houston
    case washington
    case atlanta
    case boston
    case phoenix
    case sanFrancisco
    case seattle
    case detroit
    case sanDiego
    case minneapolis
    case tampa
    case denver
    case brooklyn
    case queens
    case baltimore
    case saintLouis
    case riverside
    case lasVegas
    case portland
    case sanAntonio
    case sacramento
    case sanJose
    case orlando
    case cleveland
    case pittsburgh
    case manhattan
    case cincinnati
    case austin
    case kansasCity
    case indianapolis
    case columbus
    case virginiaBeach
    case bronx
    case charlotte
    case milwaukee
    case providence
    case jacksonville
    case memphis
    case nashville
    case saltLakeCity
    case richmond
    case newOrleans
    case raleigh
    case louisville
    case oklahomaCity
}
